---
namespace: superset

stack:
  defines: process-group
  metadata:
    name: Superset
    description: |
      Apache Superset - Open Source Data Visualization and Business Intelligence Platform

      Apache Superset is a powerful open-source data visualization and business intelligence (BI) platform that empowers organizations to explore and analyze their data with ease. With its intuitive interface and robust features, Superset is the go-to solution for data professionals, analysts, and decision-makers seeking actionable insights from their data.

      ---

      Notes:

      Default username/password: admin/admin

      | Variable            | Description                               | Default                                      |
      | ------------------- | ----------------------------------------- | -------------------------------------------- |
      | project_name        | default project name                      | Monk Superset                                |
    tags: visualization, analytics, data organization, data modeling, dashboards
    website: https://superset.apache.org/
    publisher: monk.io
    icon: https://superset.apache.org/img/superset-logo-horiz.svg
    source: https://github.com/apache/superset
  runnable-list:
    - superset/db
    - superset/rds
    - superset/superset
    - superset/superset-init
    - superset/superset-beat
    - superset/superset-worker
  variables:
    project_name:
      type: string
      value: Monk SuperSet
