---
namespace: superset

stack:
  defines: process-group
  metadata:
    name: Superset
    description: |
      In general, a superset refers to a set that contains all the elements of one or more other sets. It is a broader or more comprehensive collection of items that includes every member of the original sets.

      In mathematics, a superset is a set that contains all the elements of another set. For example, the set of natural numbers is a superset of the set of even numbers, because every even number is a natural number. Similarly, the set of real numbers is a superset of the set of integers.

      In fitness, a superset is a type of exercise that involves performing two different exercises back-to-back with little to no rest in between. For example, doing a set of bicep curls followed immediately by a set of tricep extensions would be considered a superset.

      In database management, a superset is a collection of tables or other database objects that are grouped together for a specific purpose. For example, a database might have a superset of tables that are all related to customer information.

      Overall, the term superset is used to indicate a broader or more comprehensive collection of items, whether in mathematics, fitness, database management, or other areas.

      ---

      Notes:

      Default username/password: admin/admin

      | Variable            | Description                               | Default                                      |
      | ------------------- | ----------------------------------------- | -------------------------------------------- |
      | project_name        | default project name                      | Monk Superset                                |
    tags: database management, mathematics, data organization, exercise, fitness, set theory, weightlifting, bodybuilding, workout, data modeling
    website: https://superset.apache.org/
    publisher: monk.io
    icon: https://superset.apache.org/img/superset-logo-horiz.svg
    source: https://github.com/apache/superset
  runnable-list:
    - superset/db
    - superset/rds
    - superset/superset
    - superset/superset-init
    - superset/superset-beat
    - superset/superset-worker
  variables:
    project_name:
      type: string
      value: Monk SuperSet
